<span class="hljs-attribute">name</span>: Update README

<span class="yaml"><span class="hljs-attr">on:</span>  
  <span class="hljs-attr">schedule:</span>  
    <span class="hljs-bullet">-</span> <span class="hljs-attr">cron:</span> <span class="hljs-string">'*/30 * * * *'</span>  
  <span class="hljs-attr">workflow_dispatch:</span>

<span class="hljs-attr">jobs:</span>  
  <span class="hljs-attr">build:</span>  
    <span class="hljs-attr">runs-on:</span> <span class="hljs-string">ubuntu-latest</span>  
    <span class="hljs-attr">name:</span> <span class="hljs-string">Update</span> <span class="hljs-string">this</span> <span class="hljs-string">repo's</span> <span class="hljs-string">README</span> <span class="hljs-string">with</span> <span class="hljs-string">recent</span> <span class="hljs-string">activity</span>

    <span class="hljs-attr">steps:</span>  
      <span class="hljs-bullet">-</span> <span class="hljs-attr">uses:</span> <span class="hljs-string">actions/checkout@v2</span>  
      <span class="hljs-bullet">-</span> <span class="hljs-attr">uses:</span> <span class="hljs-string">jamesgeorge007/github-activity-readme@master</span>  
        <span class="hljs-attr">env:</span>  
          <span class="hljs-attr">GITHUB_TOKEN:</span> <span class="hljs-string">${{</span> <span class="hljs-string">secrets.GITHUB_TOKEN</span> <span class="hljs-string">}}</span></span>
